export enum EmploymentType {
    FULL_TIME = "FULL_TIME",
    PART_TIME = "PART_TIME",
    SELF_EMPLOYED = "SELF_EMPLOYED",
    FREELANCE = "FREELANCE",
    CONTRACT = "CONTRACT",
    INTERNSHIP = "INTERNSHIP",
    APPRENTICESHIP = "APPRENTICESHIP",
    TEMPORARY_CIVIL_SERVANT = "TEMPORARY_CIVIL_SERVANT",
    DIRECT_CONTRACT = "DIRECT_CONTRACT",
    LIFETIME_CIVIL_SERVANT = "LIFETIME_CIVIL_SERVANT",
    CO_OP = "CO_OP"
  }
  