name: Build Angular Image and Push to GHCR + Update Config Repo

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Needed to read existing tags

      - name: Get next semantic version
        id: semver
        run: |
          # Get latest tag (defaults to v1.0.0 if none)
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")

          echo "Last tag: $LAST_TAG"

          # Strip the leading 'v'
          VERSION_NUM=${LAST_TAG#v}

          # Split version
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION_NUM"

          # Increment PATCH
          PATCH=$((PATCH + 1))

          NEW_VERSION="v${MAJOR}.${MINOR}.${PATCH}"
          echo "New version: $NEW_VERSION"

          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}
        run: |
          IMAGE=$IMAGE_NAME:${{ env.VERSION }}
          LATEST=$IMAGE_NAME:latest

          echo "Building image $IMAGE"

          export DOCKER_BUILDKIT=1
          docker build -t $IMAGE -t $LATEST -f Dockerfile.build .
          docker push $IMAGE
          docker push $LATEST

      - name: Create and push new tag
        run: |
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}

      # ---------------------------------------------
      # UPDATE CONFIG REPO WITH NEW IMAGE VERSION
      # ---------------------------------------------
      - name: Checkout config/deploy repo
        uses: actions/checkout@v4
        with:
          repository: lkhadma-ma/mfe-user-deploy
          ref: master
          token: ${{ secrets.PAT_GITHUB_TOKEN }}
          path: deploy-repo

      - name: Update image.yml with new version
        run: |
          cat > deploy-repo/image.yml <<EOF
          app:
            version: "${{ env.VERSION }}"
            name: angular-app
            registry: ghcr.io/${{ github.repository }}
          EOF

      - name: Commit and push change
        working-directory: deploy-repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add image.yml
          git commit -m "chore: update image version to ${{ env.VERSION }}"
          git push origin master

      - name: Tag deploy repo with version
        working-directory: deploy-repo
        run: |
          git tag "${{ env.VERSION }}"
          git push origin "${{ env.VERSION }}"
