name: Build Angular Image and Push to GHCR + Update Config Repo

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}
        run: |
          VERSION=$(date +%Y%m%d%H%M)
          IMAGE=$IMAGE_NAME:$VERSION
          LATEST=$IMAGE_NAME:latest

          echo "Building image $IMAGE"

          export DOCKER_BUILDKIT=1
          docker build -t $IMAGE -t $LATEST -f ci/Dockerfile.build .
          docker push $IMAGE
          docker push $LATEST

          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # ---------------------------------------------
      # UPDATE CONFIG REPO WITH NEW IMAGE VERSION
      # ---------------------------------------------
      - name: Checkout config/deploy repo
        uses: actions/checkout@v4
        with:
          repository: lkhadma-ma/mfe-user-deploy
          token: ${{ secrets.PAT_GITHUB_TOKEN }}
          path: deploy-repo

      - name: Update image.yml with new version
        run: |
          cat > deploy-repo/image.yml <<EOF
          app:
            version: "${{ env.VERSION }}"
            name: angular-app
            registry: ghcr.io/${{ github.repository }}
          EOF

      - name: Commit and push change
        working-directory: deploy-repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add image.yml
          git commit -m "chore: update image version to ${{ env.VERSION }}"
          git push origin main

      # Optional: create a tag in deploy repo 
      - name: Tag deploy repo with version
        working-directory: deploy-repo
        run: |
          git tag "v${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"
